package io.kurumi.ntt.utils;

import cn.hutool.core.util.ArrayUtil;
import cn.hutool.http.HtmlUtil;
import cn.hutool.json.JSONObject;
import io.kurumi.ntt.Launcher;
import io.kurumi.ntt.fragment.Fragment;

public class Html {

		public static String escapeAll(String text) {
				
				return HtmlUtil.escape(text)
						.replace(" ","&nbsp;")
						.replace("¡","&iexcl;")
						.replace("¢","&cent;")
						.replace("£","&pound;")
						.replace("¤","&curren;")
						.replace("¥","&yen;")
						.replace("¦","&brvbar;")
						.replace("§","&sect;")
						.replace("¨","&uml;")
						.replace("©","&copy;")
						.replace("ª","&ordf;")
						.replace("«","&laquo;")
						.replace("¬","&not;")
						.replace("soft","&shy;")
						.replace("®","&reg;")
						.replace("¯","&macr;")
						.replace("°","&deg;")
						.replace("±","&plusmn;")
						.replace("²","&sup2;")
						.replace("³","&sup3;")
						.replace("´","&acute;")
						.replace("µ","&micro;")
						.replace("¶","&para;")
						.replace("·","&middot;")
						.replace("¸","&cedil;")
						.replace("¹","&sup1;")
						.replace("º","&ordm;")
						.replace("»","&raquo;")
						.replace("¼","&frac14;")
						.replace("½","&frac12;")
						.replace("¾","&frac34;")
						.replace("¿","&iquest;")
						.replace("×","&times;")
						.replace("÷","&divide;")
						.replace("À","&Agrave;")
						.replace("Á","&Aacute;")
						.replace("Â","&Acirc;")
						.replace("Ã","&Atilde;")
						.replace("Ä","&Auml;")
						.replace("Å","&Aring;")
						.replace("Æ","&AElig;")
						.replace("Ç","&Ccedil;")
						.replace("È","&Egrave;")
						.replace("É","&Eacute;")
						.replace("Ê","&Ecirc;")
						.replace("Ë","&Euml;")
						.replace("Ì","&Igrave;")
						.replace("Í","&Iacute;")
						.replace("Î","&Icirc;")
						.replace("Ï","&Iuml;")
						.replace("Ð","&ETH;")
						.replace("Ñ","&Ntilde;")
						.replace("Ò","&Ograve;")
						.replace("Ó","&Oacute;")
						.replace("Ô","&Ocirc;")
						.replace("Õ","&Otilde;")
						.replace("Ö","&Ouml;")
						.replace("Ø","&Oslash;")
						.replace("Ù","&Ugrave;")
						.replace("Ú","&Uacute;")
						.replace("Û","&Ucirc;")
						.replace("Ü","&Uuml;")
						.replace("Ý","&Yacute;")
						.replace("Þ","&THORN;")
						.replace("ß","&szlig;")
						.replace("à","&agrave;")
						.replace("á","&aacute;")
						.replace("â","&acirc;")
						.replace("ã","&atilde;")
						.replace("ä","&auml;")
						.replace("å","&aring;")
						.replace("æ","&aelig;")
						.replace("ç","&ccedil;")
						.replace("è","&egrave;")
						.replace("é","&eacute;")
						.replace("ê","&ecirc;")
						.replace("ë","&euml;")
						.replace("ì","&igrave;")
						.replace("í","&iacute;")
						.replace("î","&icirc;")
						.replace("ï","&iuml;")
						.replace("ð","&eth;")
						.replace("ñ","&ntilde;")
						.replace("ò","&ograve;")
						.replace("ó","&oacute;")
						.replace("ô","&ocirc;")
						.replace("õ","&otilde;")
						.replace("ö","&ouml;")
						.replace("ø","&oslash;")
						.replace("ù","&ugrave;")
						.replace("ú","&uacute;")
						.replace("û","&ucirc;")
						.replace("ü","&uuml;")
						.replace("ý","&yacute;")
						.replace("þ","&thorn;")
						.replace("ÿ","&yuml;")
						.replace("∀","&forall;")
						.replace("∂","&part;")
						.replace("∃","&exists;")
						.replace("∅","&empty;")
						.replace("∇","&nabla;")
						.replace("∈","&isin;")
						.replace("∉","&notin;")
						.replace("∋","&ni;")
						.replace("∏","&prod;")
						.replace("∑","&sum;")
						.replace("−","&minus;")
						.replace("∗","&lowast;")
						.replace("√","&radic;")
						.replace("∝","&prop;")
						.replace("∞","&infin;")
						.replace("∠","&ang;")
						.replace("∧","&and;")
						.replace("∨","&or;")
						.replace("∩","&cap;")
						.replace("∪","&cup;")
						.replace("∫","&int;")
						.replace("∴","&there4;")
						.replace("∼","&sim;")
						.replace("≅","&cong;")
						.replace("≈","&asymp;")
						.replace("≠","&ne;")
						.replace("≡","&equiv;")
						.replace("≤","&le;")
						.replace("≥","&ge;")
						.replace("⊂","&sub;")
						.replace("⊃","&sup;")
						.replace("⊄","&nsub;")
						.replace("⊆","&sube;")
						.replace("⊇","&supe;")
						.replace("⊕","&oplus;")
						.replace("⊗","&otimes;")
						.replace("⊥","&perp;")
						.replace("⋅","&sdot;")
						.replace("Α","&Alpha;")
						.replace("Β","&Beta;")
						.replace("Γ","&Gamma;")
						.replace("Δ","&Delta;")
						.replace("Ε","&Epsilon;")
						.replace("Ζ","&Zeta;")
						.replace("Η","&Eta;")
						.replace("Θ","&Theta;")
						.replace("Ι","&Iota;")
						.replace("Κ","&Kappa;")
						.replace("Λ","&Lambda;")
						.replace("Μ","&Mu;")
						.replace("Ν","&Nu;")
						.replace("Ξ","&Xi;")
						.replace("Ο","&Omicron;")
						.replace("Π","&Pi;")
						.replace("Ρ","&Rho;")
						.replace(" ","undefined")
						.replace("Σ","&Sigma;")
						.replace("Τ","&Tau;")
						.replace("Υ","&Upsilon;")
						.replace("Φ","&Phi;")
						.replace("Χ","&Chi;")
						.replace("Ψ","&Psi;")
						.replace("Ω","&Omega;")
						.replace("α","&alpha;")
						.replace("β","&beta;")
						.replace("γ","&gamma;")
						.replace("δ","&delta;")
						.replace("ε","&epsilon;")
						.replace("ζ","&zeta;")
						.replace("η","&eta;")
						.replace("θ","&theta;")
						.replace("ι","&iota;")
						.replace("κ","&kappa;")
						.replace("λ","&lambda;")
						.replace("μ","&mu;")
						.replace("ν","&nu;")
						.replace("ξ","&xi;")
						.replace("ο","&omicron;")
						.replace("π","&pi;")
						.replace("ρ","&rho;")
						.replace("ς","&sigmaf;")
						.replace("σ","&sigma;")
						.replace("τ","&tau;")
						.replace("υ","&upsilon;")
						.replace("φ","&phi;")
						.replace("χ","&chi;")
						.replace("ψ","&psi;")
						.replace("ω","&omega;")
						.replace("ϑ","&thetasym;")
						.replace("ϒ","&upsih;")
						.replace("ϖ","&piv;")
						.replace("Œ","&OElig;")
						.replace("œ","&oelig;")
						.replace("Š","&Scaron;")
						.replace("š","&scaron;")
						.replace("Ÿ","&Yuml;")
						.replace("ƒ","&fnof;")
						.replace("ˆ","&circ;")
						.replace("˜","&tilde;")
						.replace(" ","&ensp;")
						.replace(" ","&emsp;")
						.replace(" ","&thinsp;")
						.replace("‌","&zwnj;")
						.replace("‍","&zwj;")
						.replace("‎","&lrm;")
						.replace("‏","&rlm;")
						.replace("–","&ndash;")
						.replace("—","&mdash;")
						.replace("‘","&lsquo;")
						.replace("’","&rsquo;")
						.replace("‚","&sbquo;")
						.replace("“","&ldquo;")
						.replace("”","&rdquo;")
						.replace("„","&bdquo;")
						.replace("†","&dagger;")
						.replace("‡","&Dagger;")
						.replace("•","&bull;")
						.replace("…","&hellip;")
						.replace("‰","&permil;")
						.replace("′","&prime;")
						.replace("″","&Prime;")
						.replace("‹","&lsaquo;")
						.replace("›","&rsaquo;")
						.replace("‾","&oline;")
						.replace("€","&euro;")
						.replace("™","&trade;")
						.replace("←","&larr;")
						.replace("↑","&uarr;")
						.replace("→","&rarr;")
						.replace("↓","&darr;")
						.replace("↔","&harr;")
						.replace("↵","&crarr;")
						.replace("⌈","&lceil;")
						.replace("⌉","&rceil;")
						.replace("⌊","&lfloor;")
						.replace("⌋","&rfloor;")
						.replace("◊","&loz;")
						.replace("♠","&spades;")
						.replace("♣","&clubs;")
						.replace("♥","&hearts;")
						.replace("♦","&diams;");
				
		}
		
		public static String unescape(String text) {
				
				return HtmlUtil.unescape(text)
						.replace("&nbsp;"," ")
						.replace("&iexcl;","¡")
						.replace("&cent;","¢")
						.replace("&pound;","£")
						.replace("&curren;","¤")
						.replace("&yen;","¥")
						.replace("&brvbar;","¦")
						.replace("&sect;","§")
						.replace("&uml;","¨")
						.replace("&copy;","©")
						.replace("&ordf;","ª")
						.replace("&laquo;","«")
						.replace("&not;","¬")
						.replace("&shy;","soft")
						.replace("&reg;","®")
						.replace("&macr;","¯")
						.replace("&deg;","°")
						.replace("&plusmn;","±")
						.replace("&sup2;","²")
						.replace("&sup3;","³")
						.replace("&acute;","´")
						.replace("&micro;","µ")
						.replace("&para;","¶")
						.replace("&middot;","·")
						.replace("&cedil;","¸")
						.replace("&sup1;","¹")
						.replace("&ordm;","º")
						.replace("&raquo;","»")
						.replace("&frac14;","¼")
						.replace("&frac12;","½")
						.replace("&frac34;","¾")
						.replace("&iquest;","¿")
						.replace("&times;","×")
						.replace("&divide;","÷")
						.replace("&Agrave;","À")
						.replace("&Aacute;","Á")
						.replace("&Acirc;","Â")
						.replace("&Atilde;","Ã")
						.replace("&Auml;","Ä")
						.replace("&Aring;","Å")
						.replace("&AElig;","Æ")
						.replace("&Ccedil;","Ç")
						.replace("&Egrave;","È")
						.replace("&Eacute;","É")
						.replace("&Ecirc;","Ê")
						.replace("&Euml;","Ë")
						.replace("&Igrave;","Ì")
						.replace("&Iacute;","Í")
						.replace("&Icirc;","Î")
						.replace("&Iuml;","Ï")
						.replace("&ETH;","Ð")
						.replace("&Ntilde;","Ñ")
						.replace("&Ograve;","Ò")
						.replace("&Oacute;","Ó")
						.replace("&Ocirc;","Ô")
						.replace("&Otilde;","Õ")
						.replace("&Ouml;","Ö")
						.replace("&Oslash;","Ø")
						.replace("&Ugrave;","Ù")
						.replace("&Uacute;","Ú")
						.replace("&Ucirc;","Û")
						.replace("&Uuml;","Ü")
						.replace("&Yacute;","Ý")
						.replace("&THORN;","Þ")
						.replace("&szlig;","ß")
						.replace("&agrave;","à")
						.replace("&aacute;","á")
						.replace("&acirc;","â")
						.replace("&atilde;","ã")
						.replace("&auml;","ä")
						.replace("&aring;","å")
						.replace("&aelig;","æ")
						.replace("&ccedil;","ç")
						.replace("&egrave;","è")
						.replace("&eacute;","é")
						.replace("&ecirc;","ê")
						.replace("&euml;","ë")
						.replace("&igrave;","ì")
						.replace("&iacute;","í")
						.replace("&icirc;","î")
						.replace("&iuml;","ï")
						.replace("&eth;","ð")
						.replace("&ntilde;","ñ")
						.replace("&ograve;","ò")
						.replace("&oacute;","ó")
						.replace("&ocirc;","ô")
						.replace("&otilde;","õ")
						.replace("&ouml;","ö")
						.replace("&oslash;","ø")
						.replace("&ugrave;","ù")
						.replace("&uacute;","ú")
						.replace("&ucirc;","û")
						.replace("&uuml;","ü")
						.replace("&yacute;","ý")
						.replace("&thorn;","þ")
						.replace("&yuml;","ÿ")
						.replace("&forall;","∀")
						.replace("&part;","∂")
						.replace("&exists;","∃")
						.replace("&empty;","∅")
						.replace("&nabla;","∇")
						.replace("&isin;","∈")
						.replace("&notin;","∉")
						.replace("&ni;","∋")
						.replace("&prod;","∏")
						.replace("&sum;","∑")
						.replace("&minus;","−")
						.replace("&lowast;","∗")
						.replace("&radic;","√")
						.replace("&prop;","∝")
						.replace("&infin;","∞")
						.replace("&ang;","∠")
						.replace("&and;","∧")
						.replace("&or;","∨")
						.replace("&cap;","∩")
						.replace("&cup;","∪")
						.replace("&int;","∫")
						.replace("&there4;","∴")
						.replace("&sim;","∼")
						.replace("&cong;","≅")
						.replace("&asymp;","≈")
						.replace("&ne;","≠")
						.replace("&equiv;","≡")
						.replace("&le;","≤")
						.replace("&ge;","≥")
						.replace("&sub;","⊂")
						.replace("&sup;","⊃")
						.replace("&nsub;","⊄")
						.replace("&sube;","⊆")
						.replace("&supe;","⊇")
						.replace("&oplus;","⊕")
						.replace("&otimes;","⊗")
						.replace("&perp;","⊥")
						.replace("&sdot;","⋅")
						.replace("&Alpha;","Α")
						.replace("&Beta;","Β")
						.replace("&Gamma;","Γ")
						.replace("&Delta;","Δ")
						.replace("&Epsilon;","Ε")
						.replace("&Zeta;","Ζ")
						.replace("&Eta;","Η")
						.replace("&Theta;","Θ")
						.replace("&Iota;","Ι")
						.replace("&Kappa;","Κ")
						.replace("&Lambda;","Λ")
						.replace("&Mu;","Μ")
						.replace("&Nu;","Ν")
						.replace("&Xi;","Ξ")
						.replace("&Omicron;","Ο")
						.replace("&Pi;","Π")
						.replace("&Rho;","Ρ")
						.replace("undefined"," ")
						.replace("&Sigma;","Σ")
						.replace("&Tau;","Τ")
						.replace("&Upsilon;","Υ")
						.replace("&Phi;","Φ")
						.replace("&Chi;","Χ")
						.replace("&Psi;","Ψ")
						.replace("&Omega;","Ω")
						.replace("&alpha;","α")
						.replace("&beta;","β")
						.replace("&gamma;","γ")
						.replace("&delta;","δ")
						.replace("&epsilon;","ε")
						.replace("&zeta;","ζ")
						.replace("&eta;","η")
						.replace("&theta;","θ")
						.replace("&iota;","ι")
						.replace("&kappa;","κ")
						.replace("&lambda;","λ")
						.replace("&mu;","μ")
						.replace("&nu;","ν")
						.replace("&xi;","ξ")
						.replace("&omicron;","ο")
						.replace("&pi;","π")
						.replace("&rho;","ρ")
						.replace("&sigmaf;","ς")
						.replace("&sigma;","σ")
						.replace("&tau;","τ")
						.replace("&upsilon;","υ")
						.replace("&phi;","φ")
						.replace("&chi;","χ")
						.replace("&psi;","ψ")
						.replace("&omega;","ω")
						.replace("&thetasym;","ϑ")
						.replace("&upsih;","ϒ")
						.replace("&piv;","ϖ")
						.replace("&OElig;","Œ")
						.replace("&oelig;","œ")
						.replace("&Scaron;","Š")
						.replace("&scaron;","š")
						.replace("&Yuml;","Ÿ")
						.replace("&fnof;","ƒ")
						.replace("&circ;","ˆ")
						.replace("&tilde;","˜")
						.replace("&ensp;"," ")
						.replace("&emsp;"," ")
						.replace("&thinsp;"," ")
						.replace("&zwnj;","‌")
						.replace("&zwj;","‍")
						.replace("&lrm;","‎")
						.replace("&rlm;","‏")
						.replace("&ndash;","–")
						.replace("&mdash;","—")
						.replace("&lsquo;","‘")
						.replace("&rsquo;","’")
						.replace("&sbquo;","‚")
						.replace("&ldquo;","“")
						.replace("&rdquo;","”")
						.replace("&bdquo;","„")
						.replace("&dagger;","†")
						.replace("&Dagger;","‡")
						.replace("&bull;","•")
						.replace("&hellip;","…")
						.replace("&permil;","‰")
						.replace("&prime;","′")
						.replace("&Prime;","″")
						.replace("&lsaquo;","‹")
						.replace("&rsaquo;","›")
						.replace("&oline;","‾")
						.replace("&euro;","€")
						.replace("&trade;","™")
						.replace("&larr;","←")
						.replace("&uarr;","↑")
						.replace("&rarr;","→")
						.replace("&darr;","↓")
						.replace("&harr;","↔")
						.replace("&crarr;","↵")
						.replace("&lceil;","⌈")
						.replace("&rceil;","⌉")
						.replace("&lfloor;","⌊")
						.replace("&rfloor;","⌋")
						.replace("&loz;","◊")
						.replace("&spades;","♠")
						.replace("&clubs;","♣")
						.replace("&hearts;","♥")
						.replace("&diams;","♦");
				
		}
		
		public static String b(Object text) {

        return "<b>" + HtmlUtil.escape(text.toString()) + "</b>";

    }

		public static String i(Object text) {

        return "<i>" + HtmlUtil.escape(text.toString()) + "</i>";

    }


    public static String a(String text,String href) {

				if (href == null) return text;
				
        return "<a href=\"" + href + "\">" + HtmlUtil.escape(text) + "</a>";

    }

    public static String user(String text,long id) {

        if (text.isEmpty()) {

            text = " ";

        }

        return a(text,"tg://user?id=" + id);

    }

		public static String twitterUser(String text,String id) {

        if (text.isEmpty()) {

            text = " ";

        }

        return a(text,"https://twitter.com/" + id);

    }

    public static String startPayload(String text,Object... payload) {

        return startPayload(Launcher.INSTANCE,text,payload);

    }

		public static String startPayload(Fragment fragment,String text,Object... payload) {

        return a(text,"https://t.me/" + fragment.origin.me.username() + "?start=" + ArrayUtil.join(payload,"_"));

    }

		public static String json(Object code) {

        return code(new JSONObject(code).toStringPretty());

    }


    public static String code(Object code) {

        return "<code>" + HtmlUtil.escape(code.toString()) + "</code>";

    }

}
